name: Deploy Kubernetes Cluster

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set the Python version

    - name: Upgradig pip
      run: pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        pip install pulumi ediri_vultr

    - name: Log in to Pulumi
      run: pulumi login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Deploy Kubernetes cluster
      run: pulumi up --yes
      env:
        VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
